name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool libffi-dev libssl-dev python3-dev python3-venv libltdl-dev libncurses5-dev libsqlite3-dev libreadline-dev libbz2-dev libgdbm-dev zlib1g-dev uuid-dev lzma-dev libopenblas-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev ffmpeg
          
      - name: Install Python packages
        run: |
          pip install --upgrade pip
          pip install buildozer cython virtualenv
          
      - name: Build APK
        run: |
          buildozer init
          sed -i 's/^requirements =.*/requirements = python3/g' buildozer.spec
          sed -i 's/^android.permissions =.*/android.permissions = INTERNET/g' buildozer.spec
          sed -i 's/^android.api =.*/android.api = 30/g' buildozer.spec
          sed -i 's/^android.minapi =.*/android.minapi = 21/g' buildozer.spec
          sed -i 's/^android.ndk =.*/android.ndk = 23b/g' buildozer.spec
          sed -i 's/^android.accept_sdk_license =.*/android.accept_sdk_license = True/g' buildozer.spec
          yes "y" | buildozer android debug
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk
          if-no-files-found: error
